import {Input as CoolInput, InputProps} from "antd";
import {FC} from "react";
import {useOptionalFormItemContext} from "./FormItemContext";

export interface IInputProps extends Partial<InputProps> {
	/**
	 * Use placeholder generated by parent FormItem.
	 */
	usePlaceholder?: boolean
}

export const Input: FC<IInputProps> = ({usePlaceholder, ...props}) => {
	const formItemContext = useOptionalFormItemContext();
	formItemContext && usePlaceholder && (props.placeholder = formItemContext.label);
	return (
		<CoolInput {...props}/>
	);
};
